import {Metadata} from "next";

export const metadata: Metadata = {
  title: "company page",
  description: "Generated by create next app",
};

export default function Home() {

  return (
      <main className="p-24">
        company page
      </main>
  );
}
