import {Metadata} from "next";

export const metadata: Metadata = {
  title: "111",
  description: "Generated by create next app",
};

export default function Home() {

  return (
      <main className="p-24">
        main page111
      </main>
  );
}
